spring.application.name=order-service
logging.level.guru=debug
server.port=8081
guru.sfg.beer.orde.service.IsOrderAllocated.message=Order is not allocated
guru.sfg.beer.orde.service.IsOrderExists.message=Order does not exist for given id
spring.jackson.serialization.write-dates-as-timestamps=false
sfg.brewery.beer-service-host=http://localhost:8080
saga.validate-order-response=validate-order-response
saga.allocate-order-response=allocate-order-response